<a href="https://colab.research.google.com/github/E-tech-coder/DataScienceCapstoneProject/blob/Elena/ZeroShot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
!git clone https://github.com/E-tech-coder/DataScienceCapstoneProject.git

fatal: destination path 'DataScienceCapstoneProject' already exists and is not an empty directory.

In [11]:
import pandas as pd

df = pd.read_csv("/content/DataScienceCapstoneProject/df_profiles_cleansed.csv").set_index("person_id").reset_index()

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2615 entries, 0 to 2614
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   person_id           2615 non-null   int64
 1   organization        2615 non-null   object
 2   position            2615 non-null   object
 3   startDate           2615 non-null   object
 4   endDate             2615 non-null   object
 5   status              2615 non-null   object
 6   department          2615 non-null   object
 7   seniority           2615 non-null   object
 8   job_count           2615 non-null   int64
 9   job_duration_years  2615 non-null   float64
dtypes: float64(1), int64(2), object(7)
memory usage: 204.4+ KB

In [13]:
df[df["status"] == "UNKNOWN"]

Empty DataFrame
Columns: [person_id, organization, position, startDate, endDate, status, department, seniority, job_count, job_duration_years]
Index: []

In [16]:
df.iloc[200:300, :]

,person_id,organization,position,startDate,endDate,status,department,seniority,job_count,job_duration_years
200,55,Universität Zürich | University of Zurich,Akademischer Tutor,2014-02,2014-06,INACTIVE,Other,Junior,7,0.328767
201,55,Valora Group,Angestellte Verkauf,2012-08,2013-11,INACTIVE,Sales,Professional,7,1.252055
202,56,Dreamcatcher Alley,Co Owner,2007-01,2025-12,ACTIVE,Other,Management,4,18.928767
203,56,Sunstates Security,Information Security Officer,2009-01,2015-01,INACTIVE,Information Technology,Professional,4,6.002740
204,56,bells weddings,Revern Linda Bell,1999-11,2010-01,INACTIVE,Other,Professional,4,10.175342
...,...,...,...,...,...,...,...,...,...,...
295,72,Österreichisches Rotes Kreuz,Zivildienst,2016-01,2016-09,INACTIVE,Other,Junior,9,0.668493
296,72,Sölle GmbH,Zweigstellen Koordinator,2015-11,2016-02,INACTIVE,Administrative,Lead,9,0.252055
297,73,Murata Vios,Director of Product Management,2022-01,2025-12,ACTIVE,Project Management,Director,7,3.917808
298,73,Idea Evolver,Sr. Product Manager,2021-04,2021-12,INACTIVE,Project Management,Senior,7,0.668493
299,73,Smiths Medical,Senior Manager - Global Products and Product L...,2019-05,2020-12,INACTIVE,Information Technology,Senior,7,1.589041

In [ ]:
! pip install transformers

In [18]:
from transformers import pipeline

# Initialize the zero-shot classification pipeline
classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")

WARNING:torchao.kernel.intmm:Warning: Detected no triton, on systems without Triton certain kernels will not work

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Device set to use cpu

In [21]:
dpt_labels = df["department"].drop_duplicates()

In [22]:
candidate_labels = dpt_labels

In [36]:
text = ["Akademischer Tutor", "Angestellte Verkauf"]

In [37]:
result = classifier(text, candidate_labels)

In [38]:
result[0]['labels'][0]

'Administrative'

In [41]:
result

[{'sequence': 'Akademischer Tutor',
  'labels': ['Administrative',
   'Consulting',
   'Other',
   'Purchasing',
   'Human Resources',
   'Information Technology',
   'Business Development',
   'Project Management',
   'Sales',
   'Marketing',
   'Customer Support'],
  'scores': [0.6203829050064087,
   0.15448781847953796,
   0.041673313826322556,
   0.029231270775198936,
   0.027400346472859383,
   0.027313612401485443,
   0.026231469586491585,
   0.020693596452474594,
   0.01914036087691784,
   0.017669055610895157,
   0.01577627658843994]},
 {'sequence': 'Angestellte Verkauf',
  'labels': ['Purchasing',
   'Administrative',
   'Consulting',
   'Sales',
   'Marketing',
   'Customer Support',
   'Human Resources',
   'Project Management',
   'Business Development',
   'Other',
   'Information Technology'],
  'scores': [0.4175385534763336,
   0.21692919731140137,
   0.12281360477209091,
   0.0862773135304451,
   0.05061783269047737,
   0.038106054067611694,
   0.021851040422916412,
   0.01260584406554699,
   0.01252981461584568,
   0.010492642410099506,
   0.010238072834908962]}]

In [42]:
prediction = []
for i,t in enumerate(text):
  prediction.append(result[i]['labels'][0])

In [43]:
prediction

['Administrative', 'Purchasing']